import type { Metadata } from "next";
import { Providers } from "./providers";
// import localFont from "next/font/local";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen flex justify-center">
        <div className="max-w-[1024px] w-full">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
