export const mockLectures = [
  {
    sub_num: '1161',
    name: '객체지향프로그래밍',
    grade: 2,
    course_type: '학선',
    credits: 3,
    professor: '이은정',
    note: '',
    period: '월 6 7 8',
    location: '8001 컴퓨터과학전산실습실',
  },
  {
    sub_num: '1169',
    name: '데이터베이스',
    grade: 2,
    course_type: '학선',
    credits: 3,
    professor: '권준희',
    note: '수강초과',
    period: '화 1 2 3',
    location: '8510 9PC실(AI컴퓨터공학부실습실)',
  },
  {
    sub_num: '1201',
    name: '프로세스공학',
    grade: 3,
    course_type: '컴터',
    credits: 3,
    professor: '김광훈',
    note: '',
    period: '목 1 2 3',
    location: '5006 소경대전공실습(PC실)',
  },
];
