apiVersion: v1
kind: Service
metadata:
    name: nextjs-service
    namespace: nextjs
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
          nodePort: 30080
    selector:
        app: nextjs
