name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    workflow_dispatch:

env:
    DOCKER_IMAGE: heung115/my-nextjs-app
    NAMESPACE: frontend

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: 코드 체크아웃
              uses: actions/checkout@v3

            - name: Create .env file
              run: |
                  echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}" > .env
                  echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
                  echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env

            - name: env 파일 확인
              run: cat .env

            - name: Docker Hub 로그인
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Buildx 설정
              uses: docker/setup-buildx-action@v2
              with:
                  install: true

            - name: Docker 이미지 빌드 및 푸시
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
                      ${{ env.DOCKER_IMAGE }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      NODE_ENV=production

            - name: Docker 이미지 환경 변수 확인 (디버깅 용도)
              run: |
                  docker run --rm ${{ env.DOCKER_IMAGE }}:latest printenv | grep NEXT_PUBLIC_API_URL

    deploy:
        needs: build_and_push
        runs-on: ubuntu-latest
        environment:
            name: production

        steps:
            - name: 코드 체크아웃
              uses: actions/checkout@v3

            - name: Google Cloud 인증
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Google Cloud SDK 설정
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  install_components: "kubectl"

            - name: GKE 자격 증명 가져오기
              uses: google-github-actions/get-gke-credentials@v1
              with:
                  cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
                  location: ${{ secrets.GKE_ZONE }}

            - name: Kubernetes 네임스페이스 생성
              run: kubectl create namespace ${{ env.NAMESPACE }} || echo "Namespace '${{ env.NAMESPACE }}' already exists"

            - name: Kubernetes 매니페스트 적용
              run: |
                  kubectl apply -f kubernetes/deployment.yml -n ${{ env.NAMESPACE }}
                  kubectl apply -f kubernetes/service.yml -n ${{ env.NAMESPACE }}

            - name: Kubernetes 배포 이미지 업데이트
              run: |
                  kubectl set image deployment/nextjs-deployment nextjs=${{ env.DOCKER_IMAGE }}:${{ github.sha }} -n ${{ env.NAMESPACE }}
                  kubectl rollout status deployment/nextjs-deployment -n ${{ env.NAMESPACE }}
